### ISSUE TITLE
Needs patch to build on Arch Linux

### ISSUE THREAD

**Issue by traysh** [jdek/ereader-buildroot#1]
Hey,

Great work, thanks!
Are you using linux to build this? It needs a fix to build, at least on my system. I created a patch and I'd make a PR if you accept it.

**Comment by jdek** [comment]
I have been using a Linux system to build it, I just pushed 075a69e92eec964bee78d83962f20c04fbe61169 which may have fixed the problem you were having.

**Comment by jdek** [comment]
Reopen if that didn't fix it.
